shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:pk>/', views.cart_remove, name='cart_remove'),
]

shop/core/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView,\
    PasswordResetView
from django.urls import include, path

from shop import views

urlpatterns = (
    path('admin/', admin.site.urls),
    path('accounts/password_change/', views.PasswordsChangeViewCustom.as_view(), name='password_change'),
    path('accounts/password_change/success/', views.password_success, name='password_success'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/my_profile/", views.UserProfile.as_view(), name="profile"),
    path("accounts/signup/", views.SignUpView.as_view(), name="signup"),
    path("accounts/update_profile/", views.UpdateProfile.as_view(), name="update_profile"),
    path(
        'accounts/password_reset/',
        PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'accounts/password_reset_done/',
        PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'accounts/password_reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'accounts/password_reset_complete/',
        PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('__debug__/', include('debug_toolbar.urls')),
)

shop/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('<int:pk>/comment/', views.book_review, name='book_review'),
    path('genres/<int:pk>/', views.BookListGenreView.as_view(), name='books_by_genre'),
    path('author/<int:pk>/', views.BookListAuthorView.as_view(), name='books_by_author'),
    path('search/', views.book_search, name='book_search'),
    path('contact/', views.contact_form, name='contact'),
    path('login/', views.login_form, name='login'),

]

shop/cart/models.py
from django.db import models  # noqa: F401

# Create your models here.

shop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label='Количество:')
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

shop/cart/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from shop.forms import SearchForm
from shop.models import Book, Genre

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, pk):
    cart = Cart(request)
    book = get_object_or_404(Book, id=pk)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if cd['quantity'] > book.quantity_in_stock:
            messages.warning(request, f'Книга {book.title} доступна в {book.quantity_in_stock} экземплярах')
            return redirect('shop:book_detail', book.id)
        cart.add(book=book,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, pk):
    cart = Cart(request)
    book = get_object_or_404(Book, id=pk)
    cart.remove(book)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    search_form = SearchForm()
    genres = Genre.objects.all()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})

    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   'search_form': search_form,
                   'genres': genres})

shop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load bootstrap %}

{% block title %}Ваша корзина{% endblock %}

{% block header %}
Корзина ({{ cart|length }} товаров)
{% endblock %}
{% block subheader %}
Корзина
{% endblock %}
{% block content %}

    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Image</th>
                            <th>Название</th>
                            <th>Количество</th>
                            <th>Цена одной книги</th>
                            <th>Общая цена</th>
                            <th>Удалить</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for item in cart %}
                    {% with book=item.book %}
                      <tr>
                        <td class="align-middle"><img src="{% if book.image %}{{ book.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="" style="width: 50px;"></td>
                        <td class="align-middle"><a href="{% url "shop:book_detail" book.id %}">{{ book.title }}</a></td>
                        <td class="align-middle">
                          <form action="{% url "cart:cart_add" book.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.override }}
                            <button class="btn btn-sm btn-primary"><i class="fa fa-refresh"></i></button>                            {% csrf_token %}
                            {% csrf_token %}
                          </form>
                        </td>
                        <td class="align-middle num">{{ item.price }} грн.</td>
                        <td class="align-middle num">{{ item.total_price }} грн.</td>
                          <td class="align-middle">
                          <form action="{% url "cart:cart_remove" book.id %}" method="post">
                            <button class="btn btn-sm btn-primary"><i class="fa fa-times"></i></button>                            {% csrf_token %}
                          </form>
                        </td>
                      </tr>
                    {% endwith %}
                  {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Корзина</h4>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">Общая сумма</h6>
                            <h6 class="font-weight-medium">{{ cart.get_total_price|floatformat:2 }} грн.</h6>
                        </div>

                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">Всего</h5>
                            <h5 class="font-weight-bold">{{ cart.get_total_price|floatformat:2 }} грн.</h5>
                        </div>
                        <form action="{% url "orders:order_create" %}">
                            <button class="btn btn-block btn-primary my-3 py-3">Оформить заказ</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->
{% endblock %}