shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:pk>/', views.cart_remove, name='cart_remove'),
]

shop/core/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView,\
    PasswordResetView
from django.urls import include, path

from shop import views

urlpatterns = (
    path('admin/', admin.site.urls),
    path('accounts/password_change/', views.PasswordsChangeViewCustom.as_view(), name='password_change'),
    path('accounts/password_change/success/', views.password_success, name='password_success'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/my_profile/", views.UserProfile.as_view(), name="profile"),
    path("accounts/signup/", views.SignUpView.as_view(), name="signup"),
    path("accounts/update_profile/", views.UpdateProfile.as_view(), name="update_profile"),
    path(
        'accounts/password_reset/',
        PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'accounts/password_reset_done/',
        PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'accounts/password_reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'accounts/password_reset_complete/',
        PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('__debug__/', include('debug_toolbar.urls')),
)

shop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('<int:pk>/comment/', views.book_review, name='book_review'),
    path('genres/<int:pk>/', views.BookListGenreView.as_view(), name='books_by_genre'),
    path('author/<int:pk>/', views.BookListAuthorView.as_view(), name='books_by_author'),
    path('search/', views.book_search, name='book_search'),
    path('contact/', views.contact_form, name='contact'),
    path('login/', views.login_form, name='login'),

]

shop/shop/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from .tasks import review_active


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.last_name}, {self.first_name}"

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])


class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(max_length=200)

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000)
    genre = models.ManyToManyField(Genre, blank=True)
    isbn = models.CharField(max_length=13)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    book_id_in_stock = models.IntegerField(verbose_name='Номер книги на складе', null=True)
    quantity_in_stock = models.IntegerField(verbose_name='Количество книг на складе', null=True)

    class Meta:
        ordering = ['title', 'author']

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('shop:book_detail', args=[str(self.id)])


class Review(models.Model):
    book = models.ForeignKey(Book,
                             on_delete=models.CASCADE,
                             related_name='reviews')
    name = models.CharField(max_length=80, verbose_name='Ваше имя')
    email = models.EmailField(max_length=250, verbose_name='E-mail')
    body = models.TextField(verbose_name='Сообщение')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Review by {self.name} on {self.book}'

    def save(self, *args, **kwargs):
        super(Review, self).save(*args, **kwargs)
        link = self.book.get_absolute_url()
        if self.active:
            message = f'Новый отзыв к книге {self.book.title} от {self.name}. {link}'
            review_active.delay("New review", self.email, message)


class Client(AbstractUser):
    email = models.EmailField(unique=True)
    address = models.CharField(max_length=80, verbose_name='Ваш адрес.')
    first_name = models.CharField(max_length=80, verbose_name='Ваше имя')
    last_name = models.CharField(max_length=80, verbose_name='Ваша фамилия')
    city = models.CharField(max_length=80, verbose_name='Ваш город')
    postal_code = models.IntegerField(verbose_name='Индекс', null=True)
    is_staff = models.BooleanField(default=False)

    def __str__(self):
        return self.username

shop/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import Client, Review


class SearchForm(forms.Form):
    query = forms.CharField(label='')


class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=30)
    email = forms.EmailField(label='Email', max_length=30)
    message = forms.CharField(label='Сообщение', max_length=300)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['name', 'email', 'body']


class ClientCreationForm(UserCreationForm):
    class Meta:
        model = Client
        fields = ("username", "email", "password1", "password2")


class ClientChangeForm(UserChangeForm):
    class Meta:
        model = Client
        fields = ("username", "email", 'first_name', 'address', 'city', 'postal_code')


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, label='Логин')
    password = forms.CharField(max_length=63, widget=forms.PasswordInput, label='Пароль')

shop/shop/views.py
from cart.forms import CartAddProductForm

from django.contrib import messages
from django.contrib.auth import authenticate, login, views
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.postgres.search import SearchVector
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.http import require_POST


from .filters import BookFilter
from .forms import ClientCreationForm, ContactForm, LoginForm, ReviewForm, SearchForm
from .models import Author, Book, Client, Genre
from .tasks import new_review, send_contact


class BookListView(generic.ListView):
    model = Book
    template_name = 'shop/book/list.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['cart_product_form'] = CartAddProductForm()
        context['filter'] = BookFilter(self.request.GET, queryset=self.get_queryset())
        context['search_form'] = SearchForm()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        sort_by = self.request.GET.get('sort')
        sort = 'created'
        if sort_by == 'priceup':
            sort = 'price'
        elif sort_by == 'pricedown':
            sort = '-price'
        elif sort_by == 'nameup':
            sort = 'title'
        elif sort_by == 'namedown':
            sort = '-title'
        elif sort_by == 'dateup':
            sort = 'created'
        elif sort_by == 'datedown':
            sort = '-created'
        return BookFilter(self.request.GET, queryset=queryset).qs.order_by(sort).select_related('author')


class BookListGenreView(generic.ListView):
    model = Book
    template_name = 'shop/book/books_by_genre.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['cart_product_form'] = CartAddProductForm()
        context['filter'] = BookFilter(self.request.GET, queryset=self.get_queryset())
        context['search_form'] = SearchForm()
        context['genre'] = Genre.objects.get(pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        queryset = super().get_queryset().filter(genre__id=self.kwargs['pk'])
        sort_by = self.request.GET.get('sort')
        sort = 'created'
        if sort_by == 'priceup':
            sort = 'price'
        elif sort_by == 'pricedown':
            sort = '-price'
        elif sort_by == 'nameup':
            sort = 'title'
        elif sort_by == 'namedown':
            sort = '-title'
        elif sort_by == 'dateup':
            sort = 'created'
        elif sort_by == 'datedown':
            sort = '-created'
        return BookFilter(self.request.GET, queryset=queryset).qs.order_by(sort).select_related('author')


class BookListAuthorView(generic.ListView):
    model = Book
    template_name = 'shop/book/books_by_author.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['cart_product_form'] = CartAddProductForm()
        context['filter'] = BookFilter(self.request.GET, queryset=self.get_queryset())
        context['search_form'] = SearchForm()
        context['author'] = Author.objects.get(pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        queryset = super().get_queryset().filter(author__id=self.kwargs['pk'])
        sort_by = self.request.GET.get('sort')
        if sort_by == 'priceup':
            queryset = queryset.order_by('price')
        elif sort_by == 'pricedown':
            queryset = queryset.order_by('-price')
        elif sort_by == 'nameup':
            queryset = queryset.order_by('title')
        elif sort_by == 'namedown':
            queryset = queryset.order_by('-title')
        elif sort_by == 'dateup':
            queryset = queryset.order_by('created')
        elif sort_by == 'datedown':
            queryset = queryset.order_by('-created')
        return BookFilter(self.request.GET, queryset=queryset).qs.select_related('author')


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'shop/book/detail.html'

    def get_context_data(self, **kwargs):
        genres = Genre.objects.all()
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['cart_product_form'] = CartAddProductForm()
        context['search_form'] = SearchForm()
        context['genres'] = genres
        objects_list = self.object.reviews.filter(active=True)
        page_num = self.request.GET.get('page', 1)
        paginator = Paginator(objects_list, 3)
        total_comments = objects_list.count()
        try:
            page_obj = paginator.page(page_num)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        context['page_obj'] = page_obj
        if self.request.user.is_authenticated:
            context['form'] = ReviewForm(
                initial={'email': self.request.user.email, 'name': self.request.user.username}
            )
        else:
            context['form'] = ReviewForm()
        context['total_comments'] = total_comments
        return context


def book_search(request):
    form = SearchForm()
    query = None
    results = []
    cart_product_form = CartAddProductForm()

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Book.objects.annotate(
                search=SearchVector('title', 'author__last_name', 'author__first_name'),
            ).filter(search=query)

    return render(request,
                  'shop/book/search.html',
                  {'search_form': form,
                   'query': query,
                   'results': results,
                   'cart_product_form': cart_product_form,
                   })


def contact(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            send_contact.delay(name, email, message)
            data['form_is_valid'] = True
            msg = [f"Сообщение от {name} отправлено"]
            data['msg_list'] = render_to_string('shop/message_contact.html', {
                'messages': msg
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
    else:
        form = ContactForm()
    return contact(request, form, 'shop/book/contact.html')


@require_POST
def book_review(request, pk):
    book = get_object_or_404(Book, id=pk)
    review = None
    form = ReviewForm(data=request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        review.book = book
        review.save()
        message = f'Новый отзыв к книге: {book.title} от {review.name}- {review.body}'
        new_review.delay("New comment", message)

    return render(request, 'shop/book/review.html',
                  {'book': book,
                   'form': form,
                   'review': review})


class UserProfile(LoginRequiredMixin, generic.DetailView):
    model = Client
    template_name = "registration/profile.html"

    def get_context_data(self, **kwargs):
        genres = Genre.objects.all()
        context = super(UserProfile, self).get_context_data(**kwargs)
        context['cart_product_form'] = CartAddProductForm()
        context['search_form'] = SearchForm()
        context['genres'] = genres
        context['orders'] = self.object.orders.all()
        return context

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class SignUpView(generic.CreateView):
    form_class = ClientCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("shop:book_list")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)  # TODO: fix
        return super(SignUpView, self).form_valid(form)


class UpdateProfile(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Client
    fields = ["first_name", "last_name", "email", "username", "city", "address", "postal_code"]
    template_name = "registration/update_profile.html"
    success_url = reverse_lazy("profile")
    success_message = "Профиль обновлен"

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class PasswordsChangeViewCustom(views.PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('password_success')
    template_name = 'registration/change-password_custom.html'


def password_success(request):
    return render(request, 'registration/change_pass_done.html')


def custom_login_page(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            user = authenticate(

shop/shop/templates/shop/book/books_by_author.html
{% extends "shop/base.html" %}
{% load static %}
{% load bootstrap %}
{% block header %}
Книги автора "{{ author }}"
{% endblock %}
{% block subheader %}
{{ author }}
{% endblock %}
{% block sidebar %}
            <div class="col-lg-3 col-md-12">
                <div class="border-bottom mb-4 pb-4">
                    <h5 class="font-weight-semi-bold mb-4">Использовать фильтр: </h5>
                    <form method="GET">
                        {{ filter.form|bootstrap }}
                    <button type="submit" class="btn btn-primary">Поиск</button>
                    </form>
                </div>
            </div>
{% endblock %}
{% block content %}
               <div class="col-lg-9 col-md-12">
                <div class="row pb-3">
                    <div class="col-12 pb-1">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div class="dropdown ml-4">
                                <form action="{% url 'shop:books_by_author' author.id %}">
                                        <label>
                                            <select name="sort" class="form-control form-control-sm">
                                                <option value="datedown" class="dropdown-item">Сначала новые</option>
                                                <option value="dateup" class="dropdown-item">Сначала старые</option>
                                                <option value="priceup" class="dropdown-item">По возрастанию цены</option>
                                                <option value="pricedown" class="dropdown-item">По убыванию цены</option>
                                                <option value="nameup" class="dropdown-item">По названию (а-я)</option>
                                                <option value="namedown" class="dropdown-item">По названию (я-а)</option>
                                            </select>
                                        </label>
                                        <input type="submit" class="btn btn-secondary btn-sm" value="Сортировать">
                                    </form>
                            </div>
                        </div>
                    </div>

                    {% for book in object_list %}
                    <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                        <div class="card product-item border-0 mb-4">
                            <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                                <a href="{{ book.get_absolute_url }}">
                                <img class="img-fluid w-100" src="{% if book.image %}{{ book.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                                </a>
                            </div>
                            <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                                <h6 class="text-truncate mb-3"><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h6>
                                <p class="text-truncate mb-3">от {{ book.author }}</p>
                                <div class="d-flex justify-content-center">
                                    <h6>{{ book.price }} грн.</h6>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-between bg-light border">
                                <a href="{{ book.get_absolute_url }}" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                                {% if book.available %}
                                    <form action="{% url "cart:cart_add" book.id %}" method="post">
                                        {{ cart_product_form|bootstrap }}
                                        {% csrf_token %}
                                        <button class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>В корзину</button>
                                    </form>
                                {% else %}
                                    <button class="btn btn-sm  text-dark p-0"><i class="fa-solid fa-ban text-primary mr-1"></i>Нет в наличии</button>
                                {% endif %}                        </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- Pager-->
                    <div class="col-12 pb-1">
                        <nav aria-label="Page navigation">
                            {% include "shop/book/pagination.html" %}
                        </nav>
                    </div>
                </div>
            </div>
{% endblock %}

shop/shop/templates/shop/book/contact.html
<form method="post" action="{% url 'shop:contact' %}" class="js-contact-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Напишите нам</h4>
  </div>
  <div class="modal-body">
    {% include 'shop/book/contact_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
    <button type="submit" class="btn btn-primary">Отправить отзыв</button>
  </div>
</form>

shop/shop/templates/shop/book/contact_form.html
{% load bootstrap %}

{{ form|bootstrap }}

shop/shop/templates/shop/book/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% load bootstrap %}

{% block title %}{{ book.title }}{% endblock %}
{% block header %}{{ book.title }}{% endblock %}
{% block subheader %}Детали{% endblock %}

{% block content %}

    <!-- Shop Detail Start -->
    <div class="container-fluid py-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 pb-5">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner border">
                        <div class="carousel-item active">
                            <img class="w-100 h-100" src="{% if book.image %}{{ book.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                        <i class="fa fa-2x fa-angle-left text-dark"></i>
                    </a>
                    <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                        <i class="fa fa-2x fa-angle-right text-dark"></i>
                    </a>
                </div>
            </div>

            <div class="col-lg-7 pb-5">
                <h3 class="font-weight-semi-bold">{{ book.title}}</h3>
                <p>от <a href="{% url 'shop:books_by_author' book.author.id %}">{{ book.author }}</a></p>
                <h3 class="font-weight-semi-bold mb-4">{{ book.price }} грн</h3>
                <div class="d-flex mb-3">
                    <p class="text-dark font-weight-medium mb-0 mr-3">Жанры:</p>
                    {% for g in book.genre.all %}
                        <p><a href="{% url 'shop:books_by_genre' g.id %}">#{{ g.name }}</a>{% if not forloop.last %}; {% endif %}</p>
                    {% endfor %}
                </div>
                <div class="d-flex align-items-center mb-4 pt-2">
                              {% if book.available %}
                                <form action="{% url "cart:cart_add" book.id %}" method="post">
                                    {{ cart_product_form|bootstrap }}
                                    {% csrf_token %}
                                    <button class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>В корзину</button>
                                </form>
                                {% else %}
                                    <button class="btn btn-sm  text-dark p-0"><i class="fa-solid fa-ban text-primary mr-1"></i>Нет в наличии</button>
                                {% endif %}
                </div>
                <div class="d-flex pt-2">
                    <p class="text-dark font-weight-medium mb-0 mr-2">Share on:</p>
                    <div class="d-inline-flex">
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    <div class="row px-xl-5">
            <div class="col">
                <div class="nav nav-tabs justify-content-center border-secondary mb-4">
                    <a class="nav-item nav-link active" data-toggle="tab" href="#tab-pane-1">Описание</a>
                    <a class="nav-item nav-link" data-toggle="tab" href="#tab-pane-3">Отзывов {{ total_comments }}</a>
                </div>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="tab-pane-1">
                        <h4 class="mb-3">Немного про эту книгу:</h4>
                        <p>{{ book.summary }}</p>
                    </div>
                    <div class="tab-pane fade" id="tab-pane-3">
                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mb-4">{{ total_comments }} отзывов на "{{ book }}"</h4>
                                {% for review in page_obj %}
                                <div class="media mb-4">
                                    <div class="media-body">
                                        <h6>Отзыв {{ forloop.counter }} от {{ review.name }}<small> - <i>{{ review.created }}</i></small></h6>
                                        <p>{{ review.body }}</p>
                                    </div>
                                </div>
                                {% empty %}
                                <p>Еще нет комментариев</p>
                                {% endfor %}
                                {% include "shop/book/pagination.html" %}

                            </div>
                            <div class="col-md-6">
                                <h4 class="mb-4">Оставить отзыв</h4>
                                    <div class="form-group">
                                        {% include "shop/book/review_form.html" %}
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Shop Detail End -->
{% endblock %}

shop/shop/templates/shop/book/search.html
{% extends "shop/base.html" %}
{% load static %}
{% load bootstrap %}

{% block title %}Поиск{% endblock %}
{% block header %}Поиск{% endblock %}
{% block subheader %}{{ query }}: (Найдено {{ results.count}} книг){% endblock %}
{% block content %}
  {% if query %}
       <div class="col-lg-9 col-md-12">
                <div class="row pb-3">
                    {% for book in results %}
                    <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                        <div class="card product-item border-0 mb-4">
                            <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                                <a href="{{ book.get_absolute_url }}">
                                <img class="img-fluid w-100" src="{% if book.image %}{{ book.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
                                </a>
                            </div>
                            <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                                <h6 class="text-truncate mb-3"><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></h6>
                                <p class="text-truncate mb-3">от <a href="{% url 'shop:books_by_author' book.author.id %}">{{ book.author }}</a></p>
                                <div class="d-flex justify-content-center">
                                    <h6>{{ book.price }} грн.</h6>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-between bg-light border">
                                <a href="{{ book.get_absolute_url }}" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                                {% if book.available %}
                                <form action="{% url "cart:cart_add" book.id %}" method="post">
                                    {{ cart_product_form|bootstrap }}
                                    {% csrf_token %}
                                    <button class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>В корзину</button>
                                </form>
                                {% else %}
                                    <button class="btn btn-sm  text-dark p-0"><i class="fa-solid fa-ban text-primary mr-1"></i>Нет в наличии</button>
                                {% endif %}                       </div>
                        </div>
                    </div>
                    {% empty %}
                <p>По вашему запросу нет результата</p>
                 {% endfor %}
  </div>
  {% else %}
    <h1>Поиск книг</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}