shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:pk>/', views.cart_add, name='cart_add'),
    path('remove/<int:pk>/', views.cart_remove, name='cart_remove'),
]

shop/core/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView,\
    PasswordResetView
from django.urls import include, path

from shop import views

urlpatterns = (
    path('admin/', admin.site.urls),
    path('accounts/password_change/', views.PasswordsChangeViewCustom.as_view(), name='password_change'),
    path('accounts/password_change/success/', views.password_success, name='password_success'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/my_profile/", views.UserProfile.as_view(), name="profile"),
    path("accounts/signup/", views.SignUpView.as_view(), name="signup"),
    path("accounts/update_profile/", views.UpdateProfile.as_view(), name="update_profile"),
    path(
        'accounts/password_reset/',
        PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'accounts/password_reset_done/',
        PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'accounts/password_reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'accounts/password_reset_complete/',
        PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('__debug__/', include('debug_toolbar.urls')),
)

shop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('<int:pk>/comment/', views.book_review, name='book_review'),
    path('genres/<int:pk>/', views.BookListGenreView.as_view(), name='books_by_genre'),
    path('author/<int:pk>/', views.BookListAuthorView.as_view(), name='books_by_author'),
    path('search/', views.book_search, name='book_search'),
    path('contact/', views.contact_form, name='contact'),
    path('login/', views.login_form, name='login'),

]

shop/shop/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from .tasks import review_active


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.last_name}, {self.first_name}"

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])


class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(max_length=200)

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000)
    genre = models.ManyToManyField(Genre, blank=True)
    isbn = models.CharField(max_length=13)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    book_id_in_stock = models.IntegerField(verbose_name='Номер книги на складе', null=True)
    quantity_in_stock = models.IntegerField(verbose_name='Количество книг на складе', null=True)

    class Meta:
        ordering = ['title', 'author']

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('shop:book_detail', args=[str(self.id)])


class Review(models.Model):
    book = models.ForeignKey(Book,
                             on_delete=models.CASCADE,
                             related_name='reviews')
    name = models.CharField(max_length=80, verbose_name='Ваше имя')
    email = models.EmailField(max_length=250, verbose_name='E-mail')
    body = models.TextField(verbose_name='Сообщение')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Review by {self.name} on {self.book}'

    def save(self, *args, **kwargs):
        super(Review, self).save(*args, **kwargs)
        link = self.book.get_absolute_url()
        if self.active:
            message = f'Новый отзыв к книге {self.book.title} от {self.name}. {link}'
            review_active.delay("New review", self.email, message)


class Client(AbstractUser):
    email = models.EmailField(unique=True)
    address = models.CharField(max_length=80, verbose_name='Ваш адрес.')
    first_name = models.CharField(max_length=80, verbose_name='Ваше имя')
    last_name = models.CharField(max_length=80, verbose_name='Ваша фамилия')
    city = models.CharField(max_length=80, verbose_name='Ваш город')
    postal_code = models.IntegerField(verbose_name='Индекс', null=True)
    is_staff = models.BooleanField(default=False)

    def __str__(self):
        return self.username

shop/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import Client, Review


class SearchForm(forms.Form):
    query = forms.CharField(label='')


class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=30)
    email = forms.EmailField(label='Email', max_length=30)
    message = forms.CharField(label='Сообщение', max_length=300)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['name', 'email', 'body']


class ClientCreationForm(UserCreationForm):
    class Meta:
        model = Client
        fields = ("username", "email", "password1", "password2")


class ClientChangeForm(UserChangeForm):
    class Meta:
        model = Client
        fields = ("username", "email", 'first_name', 'address', 'city', 'postal_code')


class LoginForm(forms.Form):
    username = forms.CharField(max_length=63, label='Логин')
    password = forms.CharField(max_length=63, widget=forms.PasswordInput, label='Пароль')

shop/shop/views.py
from cart.forms import CartAddProductForm

from django.contrib import messages
from django.contrib.auth import authenticate, login, views
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.postgres.search import SearchVector
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.http import require_POST


from .filters import BookFilter
from .forms import ClientCreationForm, ContactForm, LoginForm, ReviewForm, SearchForm
from .models import Author, Book, Client, Genre
from .tasks import new_review, send_contact


class BookListView(generic.ListView):
    model = Book
    template_name = 'shop/book/list.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['cart_product_form'] = CartAddProductForm()
        context['filter'] = BookFilter(self.request.GET, queryset=self.get_queryset())
        context['search_form'] = SearchForm()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        sort_by = self.request.GET.get('sort')
        sort = 'created'
        if sort_by == 'priceup':
            sort = 'price'
        elif sort_by == 'pricedown':
            sort = '-price'
        elif sort_by == 'nameup':
            sort = 'title'
        elif sort_by == 'namedown':
            sort = '-title'
        elif sort_by == 'dateup':
            sort = 'created'
        elif sort_by == 'datedown':
            sort = '-created'
        return BookFilter(self.request.GET, queryset=queryset).qs.order_by(sort).select_related('author')


class BookListGenreView(generic.ListView):
    model = Book
    template_name = 'shop/book/books_by_genre.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['cart_product_form'] = CartAddProductForm()
        context['filter'] = BookFilter(self.request.GET, queryset=self.get_queryset())
        context['search_form'] = SearchForm()
        context['genre'] = Genre.objects.get(pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        queryset = super().get_queryset().filter(genre__id=self.kwargs['pk'])
        sort_by = self.request.GET.get('sort')
        sort = 'created'
        if sort_by == 'priceup':
            sort = 'price'
        elif sort_by == 'pricedown':
            sort = '-price'
        elif sort_by == 'nameup':
            sort = 'title'
        elif sort_by == 'namedown':
            sort = '-title'
        elif sort_by == 'dateup':
            sort = 'created'
        elif sort_by == 'datedown':
            sort = '-created'
        return BookFilter(self.request.GET, queryset=queryset).qs.order_by(sort).select_related('author')


class BookListAuthorView(generic.ListView):
    model = Book
    template_name = 'shop/book/books_by_author.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['cart_product_form'] = CartAddProductForm()
        context['filter'] = BookFilter(self.request.GET, queryset=self.get_queryset())
        context['search_form'] = SearchForm()
        context['author'] = Author.objects.get(pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        queryset = super().get_queryset().filter(author__id=self.kwargs['pk'])
        sort_by = self.request.GET.get('sort')
        if sort_by == 'priceup':
            queryset = queryset.order_by('price')
        elif sort_by == 'pricedown':
            queryset = queryset.order_by('-price')
        elif sort_by == 'nameup':
            queryset = queryset.order_by('title')
        elif sort_by == 'namedown':
            queryset = queryset.order_by('-title')
        elif sort_by == 'dateup':
            queryset = queryset.order_by('created')
        elif sort_by == 'datedown':
            queryset = queryset.order_by('-created')
        return BookFilter(self.request.GET, queryset=queryset).qs.select_related('author')


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'shop/book/detail.html'

    def get_context_data(self, **kwargs):
        genres = Genre.objects.all()
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['cart_product_form'] = CartAddProductForm()
        context['search_form'] = SearchForm()
        context['genres'] = genres
        objects_list = self.object.reviews.filter(active=True)
        page_num = self.request.GET.get('page', 1)
        paginator = Paginator(objects_list, 3)
        total_comments = objects_list.count()
        try:
            page_obj = paginator.page(page_num)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        context['page_obj'] = page_obj
        if self.request.user.is_authenticated:
            context['form'] = ReviewForm(
                initial={'email': self.request.user.email, 'name': self.request.user.username}
            )
        else:
            context['form'] = ReviewForm()
        context['total_comments'] = total_comments
        return context


def book_search(request):
    form = SearchForm()
    query = None
    results = []
    cart_product_form = CartAddProductForm()

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Book.objects.annotate(
                search=SearchVector('title', 'author__last_name', 'author__first_name'),
            ).filter(search=query)

    return render(request,
                  'shop/book/search.html',
                  {'search_form': form,
                   'query': query,
                   'results': results,
                   'cart_product_form': cart_product_form,
                   })


def contact(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            send_contact.delay(name, email, message)
            data['form_is_valid'] = True
            msg = [f"Сообщение от {name} отправлено"]
            data['msg_list'] = render_to_string('shop/message_contact.html', {
                'messages': msg
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def contact_form(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
    else:
        form = ContactForm()
    return contact(request, form, 'shop/book/contact.html')


@require_POST
def book_review(request, pk):
    book = get_object_or_404(Book, id=pk)
    review = None
    form = ReviewForm(data=request.POST)
    if form.is_valid():
        review = form.save(commit=False)
        review.book = book
        review.save()
        message = f'Новый отзыв к книге: {book.title} от {review.name}- {review.body}'
        new_review.delay("New comment", message)

    return render(request, 'shop/book/review.html',
                  {'book': book,
                   'form': form,
                   'review': review})


class UserProfile(LoginRequiredMixin, generic.DetailView):
    model = Client
    template_name = "registration/profile.html"

    def get_context_data(self, **kwargs):
        genres = Genre.objects.all()
        context = super(UserProfile, self).get_context_data(**kwargs)
        context['cart_product_form'] = CartAddProductForm()
        context['search_form'] = SearchForm()
        context['genres'] = genres
        context['orders'] = self.object.orders.all()
        return context

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class SignUpView(generic.CreateView):
    form_class = ClientCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("shop:book_list")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)  # TODO: fix
        return super(SignUpView, self).form_valid(form)


class UpdateProfile(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Client
    fields = ["first_name", "last_name", "email", "username", "city", "address", "postal_code"]
    template_name = "registration/update_profile.html"
    success_url = reverse_lazy("profile")
    success_message = "Профиль обновлен"

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class PasswordsChangeViewCustom(views.PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('password_success')
    template_name = 'registration/change-password_custom.html'


def password_success(request):
    return render(request, 'registration/change_pass_done.html')


def custom_login_page(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            user = authenticate(

shop/shop/templates/shop/base.html
{% load static %}
{% load bootstrap %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Книжный{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">


    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/login.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">


    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>

        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="{% url 'shop:book_list' %}" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">К</span>нижный</h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="{% url "shop:book_search" %}" method="GET">
                    <div class="input-group">
                        <div class="input-group-append">
                            {{ search_form.query }}
                            <span class="input-group-text bg-transparent text-primary">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="{% url "cart:cart_detail" %}" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge">{{ cart|length }}</span>
                </a>
            </div>
        </div>
    </div>

    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Жанры</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1">
                    <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                        <a href="{% url "shop:book_list" %}" class="nav-item nav-link">Все книги</a>
                        {% for genre in genres %}
                            <a href="{% url "shop:books_by_genre" genre.id %}" class="nav-item nav-link">{{ genre.name }}</a>
                        {% endfor %}
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="{% url 'shop:book_list' %}" class="nav-item nav-link">Домой</a>
                            <a href="" data-bs-toggle="modal" data-bs-target="#modal-contact" data-url="{% url 'shop:contact' %}" class="nav-item nav-link js-contact-form">Связаться с нами</a>
                        </div>
                        <div class="navbar-nav ml-auto py-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'profile' %}">Профиль {{ user.username }}</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'logout' %}">Выйти</a></li>
                        {% else %}
                            <a href="" data-bs-toggle="modal" data-bs-target="#modal-login" data-url="{% url 'shop:login' %}" class="nav-item nav-link js-login-form">Вход</a>
                            <a href="{% url 'signup' %}" class="nav-item nav-link">Регистрация</a>
                        {% endif %}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->

    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">{% block header %}Our Shop{% endblock %}</h1>
            <div class="d-inline-flex">
                <p class="m-0"><a href="{% url 'shop:book_list' %}">Домой</a></p>
                <p class="m-0 px-2">-</p>
                <p class="m-0">{% block subheader %}{% endblock %}</p>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Django Messages -->
    <div class="container-fluid p-0" id="popup-messages-content">
        {% include 'shop/message.html' %}
    </div>
    <!-- Modal contact -->
    <div class="modal fade" id="modal-contact">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
    <!-- Modal login -->
    <div class="modal fade" id="modal-login">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
    <!-- Shop Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <!-- Shop Sidebar Start -->
            {% block sidebar %}
            {% endblock %}
            <!-- Shop Sidebar End -->


            <!-- Shop Product Start -->
            {% block content %}
            {% endblock %}
            <!-- Shop Product End -->
        </div>
    </div>
    <!-- Shop End -->


    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">К</span>нижный</h1>
                </a>
                <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Хрещатик Street, Киев, Слава Украине</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>admin@admin.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="{% url 'shop:book_list' %}">Книжный</a>. Никакие права не защищены)
                </p>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static "lib/easing/easing.min.js" %}"></script>
    <script src="{% static "lib/owlcarousel/owl.carousel.min.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>


    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>

    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/login.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</body>

</html>

shop/shop/templates/shop/message.html
{% for message in messages %}
    <div class="container-fluid p-0">
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    </div>
</div>
{% endfor %}

shop/shop/templates/shop/message_contact.html
{% for message in messages %}
    <div class="container-fluid p-0">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
          {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    </div>
</div>
{% endfor %}